package com.sg.vendingmachine.dto;

public enum SnackType {
    HOT_CHEETOS, HOT_FRIES,
    LAYS_POTATO_CHIPS, RUFFLES_CHEDDAR_CHIPS,
    CHIPS_AHOY_COOKIES, OREOS,
    TWIX_BAR, REESES,
    POPTART, CHOCOLATE_PROTEIN_BAR
}
